# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-07 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 12, 7, 14, 29, 28, 855998, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
