# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-16 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_work_coverimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='new/')),
            ],
        ),
        migrations.AlterField(
            model_name='work',
            name='coverImage',
            field=models.FileField(upload_to='new/'),
        ),
        migrations.AddField(
            model_name='workimage',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainsite.Work'),
        ),
    ]
